name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - testactions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      # Option A: use your modified "build" script (build = open-next build)
      - name: Build (OpenNext Cloudflare)
        run: npm run build

      # Option B (alternative) direct invocation:
      # - run: npx @opennextjs/cloudflare build

      - name: Verify build output
        run: ls -R .open-next | head -100

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          # If your wrangler.jsonc needs account_id via env secrets, set them here
          # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_ENV: production
