name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the repository content

      - name: Install Dependencies
        run: npm install # Or yarn install / pnpm install, depending on your package manager

      - name: Build OpenNext Project
        run: npm run build # This command should trigger your Next.js/OpenNext build

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # OpenNext usually handles the entry point and configuration
          # but ensure the build output is available.
          # If your build output isn't in the root of the repo,
          # you might need to specify the 'workingDirectory' input for the action.
          # Example: workingDirectory: "out" (if your build output is in an 'out' folder)
