name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - testactions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build (OpenNext Cloudflare)
        run: npm run build:cf

      - name: Verify build output
        run: |
          echo "Listing .open-next root" && ls -al .open-next || echo ".open-next missing";
          echo "Show first files";
          find .open-next -maxdepth 2 -type f | head -50 || true

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          NODE_ENV: production
